### ISSUE TITLE
Psst

### ISSUE THREAD

**Issue by wallentx** [gricowijaya/suckless-config#1]
@gricowijaya I saw this while searching github
https://github.com/gricowijaya/suckless-config/blob/e00e52d3f91e087c7b887faaf574e5882bfec21f/.bashrc#L156

Might be useful to implement something like https://github.com/trufflesecurity/trufflehog#pre-commit-hook

**Comment by gricowijaya** [comment]
Thanks a lot for the concern I'll try to patch and implement your
suggestion of remediation with the pipeline
